workspace: ".."
project_name: "edx"
image_version: latest

ports:
  lms: 31001
  studio: 31002
  forum: 31004
  discovery: 31005
  registrar: 31008
  registrar-worker: 31009
  mysql: 32001
  mongo: 32002
  memcached: 32003
  elasticsearch: 32004
  redis: 32005
  devpi: 32006
  chrome: 32007
  firefox: 32008

repositories:
  - source: "git@github.com:edx/edx-platform.git#master"
    overrides: {}
    enabled: true
    clone: true
  - source: "git@github.com:edx/course-discovery.git#master"
    overrides: {}
    clone: false
  - source: "git@github.com:edx/registrar.git#master"
    overrides: {}

override_services:

  elasticsearch:
    image: edxops/elasticsearch:devstack
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_data:/usr/share/elasticsearch/logs

  devpi:
    image: edxops/devpi:${OPENEDX_RELEASE}
    ports:
      - "${OPENEDX_DEVPI_PORT}:${OPENEDX_DEVPI_PORT}"
    volumes:
      - devpi_data:/data

  memcached:
    image: memcached:1.4.24

  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:2.8
    command: redis-server --requirepass password
    ports:
      - "${OPENEDX_REDIS_PORT}:${OPENEDX_REDIS_PORT}"
