
version: "2.1"

services:
  
  _webservice:
    stdin_open: true
    tty: true
    environment:
      LMS_BASE_URL: "http://localhost:${OPENEDX_LMS_PORT}/"
      STUDIO_BASE_URL: "http://localhost:${OPENEDX_STUDIO_PORT}/"
      DISCOVERY_BASE_URL: "http://localhost:${OPENEDX_DISCOVERY_PORT}/"
      REGISTRAR_BASE_URL: "http://localhost:${OPENEDX_REGISTRAR_PORT}/"

  _edxapp_service:
    extends: _webservice
    image: edxops/edxapp:${OPENEDX_IMAGE_VERSION}
    environment:
      BOK_CHOY_HOSTNAME: studio
      BOK_CHOY_LMS_PORT: 18103
      BOK_CHOY_CMS_PORT: 18131
      EDXAPP_TEST_MONGO_HOST: mongo
      NO_PYTHON_UNINSTALL: 1

  _registrar_service:
    extends: _webservice
    environment:
      DB_HOST: mysql
      DB_NAME: registrar
      DB_PORT: ${OPENEDX_MYSQL_PORT}
      DB_USER: registrar001
      DB_PASSWORD: password
      LMS_HOST: http://localhost:${OPENEDX_LMS_PORT}
      MEMCACHE_HOST: memcached
      DJANGO_SETTINGS_MODULE: registrar.settings.devstack
      CELERY_ALWAYS_EAGER: 'false'
      CELERY_BROKER_TRANSPORT: redis
      CELERY_BROKER_HOSTNAME: redis:${OPENEDX_REDIS_PORT}
      CELERY_BROKER_VHOST: 10
      CELERY_BROKER_PASSWORD: password
    image: edxops/registrar:${OPENEDX_IMAGE_VERSION}
    volumes:
      - /edx/var/registrar/

  _microfrontend:
    command: bash -c 'npm install && npm run start'
    image: node:10
    environment:
      NODE_ENV: development
