#!/bin/sh

IDA=$1
IMAGE=$2

IDA_PATH=./$IDA
IMAGE_PATH=$IDA_PATH/$IMAGE_PATH

. $IDA_PATH/ida.env
. $IMAGE_PATH/image.env

BUILDCONTEXT_PATH=$IMAGE_PATH/buildcontext
mkdir -p $BUILDCONTEXT_PATH

TYPE=$MODSTACK_BUILD_IMAGE_TYPE
MAKEFILE_SRC=${TYPE}.Makefile.default
DOCKERFILE_SRC=$
MAKEFILE_DEST=$
DOCKERFILE_DEST=$

